[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = [
    "src",
]
include = [
    "jaxlayerlumos*",
]

[tool.setuptools.package-data]
jaxlayerlumos = [
    "*.json",
    "light_sources/*.csv",
    "materials/*.csv",
    "raw_materials/*.csv",
]

[project]
name = "jaxlayerlumos"
version = "0.3.5"
description = "A JAX-based Differentiable Optical and Radio Frequency Simulator for Multilayer Structures"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    {name = "Mingxuan Li", email = "mil152@pitt.edu"},
    {name = "Jungtaek Kim", email = "jungtaek.kim.mail@gmail.com"},
    {name = "Paul W. Leu", email = "pleu@pitt.edu"},
]
dependencies = [
    "jax",
    "jaxlib",
]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
]

[project.urls]
Homepage = "https://github.com/JaxLayerLumos/JaxLayerLumos"
Source = "https://github.com/JaxLayerLumos/JaxLayerLumos"

[project.optional-dependencies]
dev = [
    "matplotlib",
    "pytest",
    "wheel",
    "build",
    "twine",
    "black",
    "colour-science",
    "ipykernel",
    "nbclient",
    "nbformat",
]

benchmarking = [
    "tmm-fast",
]

examples = [
    "bayeso",
    "optax",
]
